Hello sir,
I had pushed my repo so many times but it always shoed me this error, and I tended to ignore it assuming the other filles are being push but
it was not being pushed ever since this error popped out for the first time, and unfortunately the pushes which i made are not being shown in the
repo commit history!

remote: Resolving deltas: 100% (27/27), completed with 13 local objects.
remote: error: Trace: 786320729e97337d755c31de835582178a32f0523bf2efe7bfa71d409000bc2f
remote: error: See https://gh.io/lfs for more information.
remote: error: File week_8/dataset/mnist_train.csv is 104.50 MB; this exceeds GitHub's file size limit of 100.00 MB
remote: error: GH001: Large files detected. You may want to try Git Large File Storage - https://git-lfs.github.com.
To https://github.com/Prince-vaishya/AI_workbook.git
 ! [remote rejected] main -> main (pre-receive hook declined)
error: failed to push some refs to 'https://github.com/Prince-vaishya/AI_workbook.git'
